all:
    routing:
        homepage:
            path: /
            controller: App\Controllers\Homepage::index
        test:
            path: /test
            controller: App\Controllers\Homepage::test
            